Repository citrusframework/citrus, pull requests merged in 2023-09, with the labels that each got.

#971 fix: expose test contest to inheritant test case runners
  core/citrus-base/src/main/java/org/citrusframework/DefaultTestCaseRunner.java
Labels: Type: Enhancement, Prio: High

#972 feat: static access to extractor builders
  validation/citrus-validation-json/src/main/java/org/citrusframework/validation/json/JsonPathVariableExtractor.java
  validation/citrus-validation-xml/src/main/java/org/citrusframework/validation/xml/XpathPayloadVariableExtractor.java
Labels: Type: Enhancement, Type: Feature, Prio: Medium

#987 feat(#976): Disable/Override standard Citrus reporters
  core/citrus-spring/src/main/java/org/citrusframework/reporter/ReporterConfig.java
  core/citrus-spring/src/test/java/org/citrusframework/UnitTestSupport.java
  core/citrus-spring/src/test/java/org/citrusframework/reporter/DisabledReporterConfigTest.java
  core/citrus-spring/src/test/java/org/citrusframework/reporter/OverrideReporterConfigTest.java
  core/citrus-spring/src/test/java/org/citrusframework/reporter/ReporterConfigTest.java
  src/manual/reporting.adoc
Labels: Type: Enhancement, Prio: High

#985 allow WITH sql keyword for query action
  connectors/citrus-sql/src/main/java/org/citrusframework/actions/ExecuteSQLQueryAction.java
  connectors/citrus-sql/src/test/java/org/citrusframework/actions/ExecuteSQLQueryActionTest.java
  connectors/citrus-sql/src/test/resources/org/citrusframework/actions/test-sql-query-statements.sql
Labels: Type: Bug, Prio: Medium

#996 Various documentation fixes
  endpoints/citrus-camel/src/main/java/org/citrusframework/camel/actions/CreateCamelRouteAction.java
  src/manual/actions-purge-endpoints.adoc
  src/manual/actions-purge-jms.adoc
  src/manual/actions-receive.adoc
  src/manual/actions-send.adoc
  src/manual/changes-new.adoc
  src/manual/data-dictionary.adoc
  src/manual/endpoint-adapter.adoc
  src/manual/endpoint-arquillian.adoc
  src/manual/endpoint-camel.adoc
  src/manual/endpoint-channel.adoc
  src/manual/endpoint-component.adoc
  src/manual/endpoint-direct.adoc
  src/manual/endpoint-docker.adoc
  src/manual/endpoint-ftp.adoc
  src/manual/endpoint-http.adoc
  src/manual/endpoint-jdbc.adoc
  src/manual/endpoint-jms.adoc
  src/manual/endpoint-jmx.adoc
  src/manual/endpoint-kafka.adoc
  src/manual/endpoint-kubernetes.adoc
  src/manual/endpoint-mail.adoc
  src/manual/endpoint-restdocs.adoc
  src/manual/endpoint-rmi.adoc
  src/manual/endpoint-selenium.adoc
  src/manual/endpoint-soap.adoc
  src/manual/endpoint-ssh.adoc
  src/manual/endpoint-vertx.adoc
  src/manual/endpoint-websocket.adoc
  src/manual/endpoint-zookeeper.adoc
  src/manual/endpoints.adoc
  src/manual/functions.adoc
  src/manual/message-tracing.adoc
  src/manual/reporting.adoc
  src/manual/run-xml.adoc
  src/manual/runtimes-cucumber.adoc
  src/manual/setup.adoc
  src/manual/test-actors.adoc
  src/manual/test-suite.adoc
  src/manual/validation-json.adoc
  src/manual/validation-matchers.adoc
  src/manual/validation-xml.adoc
Labels: Type: Enhancement, Prio: Medium, Type: Documentation

#1000 Feat/improve schema resolving dom xml message validator
  validation/citrus-validation-xml/src/main/java/org/citrusframework/validation/xml/schema/XmlSchemaValidation.java
  validation/citrus-validation-xml/src/test/java/org/citrusframework/validation/xml/DomXmlMessageValidatorTest.java
Labels: Type: Enhancement, Type: Maintenance, Prio: High

#1004 fix(#1003): Synchronize access to the zipEntries array cache
  core/citrus-api/src/main/java/org/citrusframework/spi/ResourcePathTypeResolver.java
Labels: Prio: High
