Repository citrusframework/citrus, pull requests merged in 2023-10, with the labels that each got.

#991 chore: remove automatic sql variable extraction
  connectors/citrus-sql/src/main/java/org/citrusframework/actions/ExecutePLSQLAction.java
  connectors/citrus-sql/src/main/java/org/citrusframework/actions/ExecuteSQLAction.java
  connectors/citrus-sql/src/main/java/org/citrusframework/actions/ExecuteSQLQueryAction.java
  connectors/citrus-sql/src/test/java/org/citrusframework/actions/ExecutePLSQLActionTest.java
  connectors/citrus-sql/src/test/java/org/citrusframework/actions/ExecuteSQLActionTest.java
  connectors/citrus-sql/src/test/java/org/citrusframework/actions/ExecuteSQLQueryActionTest.java
  connectors/citrus-sql/src/test/java/org/citrusframework/actions/dsl/ExecuteSQLQueryTestActionBuilderTest.java
Labels: Type: Enhancement, Type: Maintenance, Prio: Medium, State: WIP

#1009 update dependency versions
  .mvn/wrapper/maven-wrapper.properties
  CONTRIBUTING.md
  README.md
  connectors/citrus-selenium/pom.xml
  pom.xml
  runtime/citrus-quarkus/pom.xml
  tools/archetypes/jms/src/main/resources/archetype-resources/pom.xml
  tools/archetypes/quickstart/src/main/resources/archetype-resources/pom.xml
  tools/archetypes/soap/src/main/resources/archetype-resources/pom.xml
Labels: Prio: High, Type: Dependencies

#1017 fix(#1016): Enhance bean definition parser configuration capabilities
  core/citrus-spring/src/main/java/org/citrusframework/common/SpringXmlTestLoader.java
  core/citrus-spring/src/main/java/org/citrusframework/common/SpringXmlTestLoaderConfigurer.java
  runtime/citrus-junit5/src/test/java/org/citrusframework/junit/jupiter/integration/spring/SpringBeanXml_IT.java
  runtime/citrus-junit5/src/test/java/org/citrusframework/junit/jupiter/integration/spring/SpringBean_IT.java
  runtime/citrus-junit5/src/test/java/org/citrusframework/junit/jupiter/integration/spring/SpringXmlTestLoader_IT.java
Labels: Type: Feature, Prio: High

#1001 #997: Replace Optional.orElse() with Optional.orElseGet()
  connectors/citrus-docker/src/main/java/org/citrusframework/docker/command/ContainerCreate.java
  core/citrus-base/src/main/java/org/citrusframework/actions/AbstractAsyncTestAction.java
  core/citrus-base/src/main/java/org/citrusframework/actions/InputAction.java
  core/citrus-base/src/main/java/org/citrusframework/actions/SendMessageAction.java
  core/citrus-base/src/main/java/org/citrusframework/condition/ActionCondition.java
  core/citrus-base/src/main/java/org/citrusframework/container/AbstractActionContainer.java
  core/citrus-base/src/main/java/org/citrusframework/container/Template.java
  core/citrus-base/src/main/java/org/citrusframework/message/ZipMessage.java
  core/citrus-base/src/main/java/org/citrusframework/message/selector/DelegatingMessageSelector.java
  core/citrus-base/src/main/java/org/citrusframework/report/HtmlReporter.java
  core/citrus-base/src/main/java/org/citrusframework/report/JUnitReporter.java
  core/citrus-base/src/main/java/org/citrusframework/util/FileUtils.java
  core/citrus-base/src/main/java/org/citrusframework/validation/DefaultMessageHeaderValidator.java
  endpoints/citrus-ftp/src/main/java/org/citrusframework/ftp/client/FtpClient.java
  endpoints/citrus-ftp/src/main/java/org/citrusframework/ftp/client/SftpClient.java
  endpoints/citrus-ftp/src/main/java/org/citrusframework/ftp/server/FtpServerFtpLet.java
  endpoints/citrus-ftp/src/main/java/org/citrusframework/ftp/server/SftpServer.java
  endpoints/citrus-jms/src/main/java/org/citrusframework/jms/endpoint/JmsTopicSubscriber.java
  endpoints/citrus-kafka/src/main/java/org/citrusframework/kafka/embedded/EmbeddedKafkaServer.java
  endpoints/citrus-kafka/src/main/java/org/citrusframework/kafka/endpoint/KafkaConsumer.java
  endpoints/citrus-kafka/src/main/java/org/citrusframework/kafka/endpoint/KafkaProducer.java
  endpoints/citrus-kafka/src/main/java/org/citrusframework/kafka/message/KafkaMessageConverter.java
  endpoints/citrus-spring-integration/src/main/java/org/citrusframework/channel/selector/DispatchingMessageSelector.java
  endpoints/citrus-ssh/src/main/java/org/citrusframework/ssh/server/SshServer.java
  endpoints/citrus-ws/src/main/java/org/citrusframework/ws/client/WebServiceEndpointConfiguration.java
  runtime/citrus-junit/src/main/java/org/citrusframework/junit/JUnit4TestEngine.java
  runtime/citrus-testng/src/main/java/org/citrusframework/testng/TestNGEngine.java
  runtime/citrus-xml/src/main/java/org/citrusframework/xml/XmlTestCase.java
  runtime/citrus-yaml/src/main/java/org/citrusframework/yaml/YamlTestCase.java
  tools/maven/citrus-maven-plugin/src/main/java/org/citrusframework/mvn/plugin/CreateDocsMojo.java
  tools/maven/citrus-maven-plugin/src/main/java/org/citrusframework/mvn/plugin/CreateTestMojo.java
  tools/maven/citrus-maven-plugin/src/main/java/org/citrusframework/mvn/plugin/GenerateDocsMojo.java
  tools/maven/citrus-maven-plugin/src/main/java/org/citrusframework/mvn/plugin/GenerateTestMojo.java
  tools/test-generator/src/main/java/org/citrusframework/generate/javadsl/JavaTestGenerator.java
  tools/test-generator/src/main/java/org/citrusframework/generate/javadsl/MessagingJavaTestGenerator.java
  tools/test-generator/src/main/java/org/citrusframework/generate/xml/MessagingXmlTestGenerator.java
Labels: Type: Bug, Type: Enhancement, Prio: High

#1032 fix: Deactivate standard reporters
  core/citrus-spring/src/main/java/org/citrusframework/reporter/ReporterConfig.java
  core/citrus-spring/src/test/java/org/citrusframework/reporter/DisabledReporterConfigTest.java
  core/citrus-spring/src/test/java/org/citrusframework/reporter/ReporterConfigDisabledTest.java
  core/citrus-spring/src/test/java/org/citrusframework/reporter/ReporterConfigTest.java
  core/citrus-spring/src/test/resources/org/citrusframework/reporter/default-logger-disabled.properties
  src/manual/reporting.adoc
Labels: Prio: High

#1036 fix: Do not resolveAllFromJar on empty path
  core/citrus-api/src/main/java/org/citrusframework/spi/ResourcePathTypeResolver.java
Labels: Type: Bug, Prio: High
