Repository citrusframework/citrus, pull requests merged in 2023-11, with the labels that each got.

#1045 vulnerability in bouncycastle
  endpoints/citrus-ssh/pom.xml
  pom.xml
Labels: Type: Maintenance, Prio: High, Type: Dependencies

#1048 fix(#1046): Resolve excessive class pass scanning by caching scan res…
  core/citrus-api/src/main/java/org/citrusframework/message/MessageSelector.java
  core/citrus-api/src/main/java/org/citrusframework/spi/ResourcePathTypeResolver.java
  core/citrus-api/src/main/java/org/citrusframework/validation/ValueMatcher.java
  core/citrus-api/src/test/java/org/citrusframework/spi/ResourcePathTypeResolverTest.java
  core/citrus-api/src/test/java/org/citrusframework/spi/mocks/FooWithParams.java
  core/citrus-api/src/test/java/org/citrusframework/spi/mocks/SingletonFoo.java
  core/citrus-api/src/test/resources/META-INF/all/mocks
  core/citrus-api/src/test/resources/META-INF/mocks/singletonFoo
  core/citrus-api/src/test/resources/META-INF/mocksWithParams/fooWithParams
  core/citrus-spring/src/main/java/org/citrusframework/config/CitrusNamespaceParserRegistry.java
  runtime/citrus-yaml/src/main/java/org/citrusframework/yaml/actions/YamlTestActionBuilder.java
Labels: Type: Bug, Prio: High

#1053 fix(#1052): Provide ConversionService configuration as extra Configuration class
  core/citrus-spring/src/main/java/org/citrusframework/config/CitrusConversionServiceConfiguration.java
  core/citrus-spring/src/main/java/org/citrusframework/config/CitrusSpringConfig.java
  core/citrus-spring/src/main/java/org/citrusframework/io/CitrusResourceEditor.java
  runtime/citrus-testng/src/main/java/org/citrusframework/testng/spring/TestNGCitrusSpringSupport.java
Labels: Type: Bug, Prio: High

#1064 ci: fix flaky date function test
  core/citrus-base/src/main/java/org/citrusframework/functions/core/ChangeDateFunction.java
  core/citrus-base/src/test/java/org/citrusframework/functions/core/ChangeDateFunctionTest.java
Labels: Type: Enhancement, Type: Maintenance, Prio: High

#1065 fix: cookie on http response with status code
  endpoints/citrus-http/src/main/java/org/citrusframework/http/message/HttpMessageConverter.java
  endpoints/citrus-http/src/test/java/org/citrusframework/http/message/HttpMessageConverterTest.java
Labels: Type: Bug, Prio: High

#1067 fix: data dictionary resolve for classpath resources
  core/citrus-base/src/main/java/org/citrusframework/variable/dictionary/AbstractDataDictionary.java
  core/citrus-base/src/test/java/org/citrusframework/variable/dictionary/AbstractDataDictionaryTest.java
Labels: Type: Bug, Prio: High

#1069 chore: citrus resource wrapper for classpath resources
  core/citrus-api/src/main/java/org/citrusframework/spi/PropertiesLoader.java
  core/citrus-api/src/main/java/org/citrusframework/spi/ResourcePathTypeResolver.java
  core/citrus-base/src/main/java/org/citrusframework/variable/dictionary/AbstractDataDictionary.java
  core/citrus-spring/src/main/java/org/citrusframework/spi/CitrusResourceWrapper.java
  core/citrus-spring/src/test/java/org/citrusframework/spi/CitrusResourceWrapperTest.java
Labels: Type: Bug, Type: Maintenance, Prio: High

#1068 #1066: Improve validation and test coverage for JmsEndpointConfigParser and JmsSyncEndpointConfigParser
  endpoints/citrus-jms/src/main/java/org/citrusframework/jms/config/annotation/JmsEndpointConfigParser.java
  endpoints/citrus-jms/src/main/java/org/citrusframework/jms/config/annotation/JmsSyncEndpointConfigParser.java
  endpoints/citrus-jms/src/test/java/org/citrusframework/jms/config/annotation/JmsEndpointConfigParserExceptionTest.java
  endpoints/citrus-jms/src/test/java/org/citrusframework/jms/config/annotation/JmsSyncEndpointConfigParserExceptionTest.java
Labels: Type: Maintenance, Prio: Medium

#1074 migrate to commons lang3
  core/citrus-base/pom.xml
  core/citrus-base/src/main/java/org/citrusframework/report/JUnitReporter.java
  core/citrus-base/src/test/java/org/citrusframework/variable/dictionary/AbstractDataDictionaryTest.java
  endpoints/citrus-mail/src/main/java/org/citrusframework/mail/message/MailMessageConverter.java
  pom.xml
  validation/citrus-validation-xml/src/main/java/org/citrusframework/functions/core/EscapeXmlFunction.java
Labels: Type: Maintenance, Prio: Low, Type: Dependencies
