Repository citrusframework/citrus, pull requests merged in 2024-05, with the labels that each got.

#1162 fix: test result compatibility for simulator
  core/citrus-api/src/main/java/org/citrusframework/TestResult.java
Labels: Type: Bug, Prio: High

#1159 fix(citrus-http): accept status code interface
  endpoints/citrus-http/src/main/java/org/citrusframework/http/actions/HttpClientActionBuilder.java
  endpoints/citrus-http/src/main/java/org/citrusframework/http/actions/HttpClientResponseActionBuilder.java
  endpoints/citrus-http/src/test/java/org/citrusframework/http/actions/HttpClientActionBuilderTest.java
  endpoints/citrus-http/src/test/java/org/citrusframework/http/actions/HttpClientResponseActionBuilderTest.java
Labels: Type: Enhancement, Prio: High

#1164 fix: reformat test reporter output
  core/citrus-base/src/main/java/org/citrusframework/report/LoggingReporter.java
  core/citrus-base/src/test/java/org/citrusframework/report/LoggingReporterTest.java
Labels: Type: Enhancement, Prio: High, State: Review

#1165 deps
  pom.xml
Labels: Prio: High, Type: Dependencies

#1171 Fix: NPE in case of response header without required attribute
  connectors/citrus-openapi/src/main/java/org/citrusframework/openapi/model/v3/Oas30ModelHelper.java
  connectors/citrus-openapi/src/test/java/org/citrusframework/openapi/model/v3/Oas30ModelHelperTest.java
Labels: Type: Bug, Prio: High, State: Review
