Repository citrusframework/citrus, pull requests merged in 2024-11, with the labels that each got.

#1247 Issue #929: fix set charset for request content
  endpoints/citrus-http/src/main/java/org/citrusframework/http/interceptor/LoggingClientInterceptor.java
  endpoints/citrus-http/src/test/java/org/citrusframework/http/interceptor/LoggingClientInterceptorTest.java
Labels: Type: Bug, Prio: High, State: Review

#1248 feat: uuid v4 validation matcher
  core/citrus-base/src/main/java/org/citrusframework/validation/matcher/DefaultValidationMatcherLibrary.java
  core/citrus-base/src/main/java/org/citrusframework/validation/matcher/core/UuidV4ValidationMatcher.java
  core/citrus-base/src/test/java/org/citrusframework/validation/matcher/core/UuidV4ValidationMatcherTest.java
Labels: Type: Feature, Prio: Medium, good first issue, State: Review

#1261 add timeout to iterating action containers
  core/citrus-base/src/main/java/org/citrusframework/AbstractIteratingContainerBuilder.java
  core/citrus-base/src/main/java/org/citrusframework/container/AbstractIteratingActionContainer.java
  core/citrus-base/src/main/java/org/citrusframework/container/RepeatOnErrorUntilTrue.java
  core/citrus-base/src/test/java/org/citrusframework/container/AbstractIteratingActionContainerTest.java
  core/citrus-base/src/test/java/org/citrusframework/container/RepeatOnErrorUntilTrueTest.java
  core/citrus-spring/src/main/java/org/citrusframework/config/xml/AbstractIteratingTestContainerFactoryBean.java
  core/citrus-spring/src/main/java/org/citrusframework/config/xml/AbstractIterationTestActionParser.java
  core/citrus-spring/src/main/java/org/citrusframework/config/xml/RepeatOnErrorUntilTrueParser.java
  core/citrus-spring/src/main/resources/org/citrusframework/schema/citrus-testcase.xsd
  core/citrus-spring/src/test/java/org/citrusframework/config/xml/IterateParserTest.java
  core/citrus-spring/src/test/java/org/citrusframework/config/xml/RepeatOnErrorUntilTrueParserTest.java
  core/citrus-spring/src/test/java/org/citrusframework/config/xml/RepeatUntilTrueParserTest.java
  core/citrus-spring/src/test/resources/org/citrusframework/config/xml/IterateParserTest-context.xml
  core/citrus-spring/src/test/resources/org/citrusframework/config/xml/RepeatOnErrorUntilTrueParserTest-context.xml
  core/citrus-spring/src/test/resources/org/citrusframework/config/xml/RepeatUntilTrueParserTest-context.xml
  endpoints/citrus-kafka/src/test/resources/org/citrusframework/kafka/integration/KafkaEndpointIT_selectiveMessage.xml
  endpoints/citrus-kafka/src/test/resources/org/citrusframework/kafka/integration/KafkaEndpointIT_singleMessage.xml
Labels: Type: Enhancement, Prio: High, State: Review

#1270 upgrade to spring v6.2.0
  endpoints/citrus-http/src/main/java/org/citrusframework/http/client/HttpResponseErrorHandler.java
  endpoints/citrus-http/src/test/java/org/citrusframework/http/server/HttpServerTest.java
  pom.xml
  tools/restdocs/src/main/java/org/citrusframework/restdocs/http/CachedBodyHttpRequest.java
  tools/restdocs/src/main/java/org/citrusframework/restdocs/http/RestDocConfiguredHttpRequest.java
  tools/restdocs/src/test/java/org/citrusframework/restdocs/http/AbstractHttpRequestTest.java
  tools/restdocs/src/test/java/org/citrusframework/restdocs/http/CachedBodyHttpRequestTest.java
  tools/restdocs/src/test/java/org/citrusframework/restdocs/http/RestDocConfiguredHttpRequestTest.java
Labels: Prio: High, Type: Dependencies
