Repository citrusframework/citrus, pull requests merged in 2024-10, with the labels that each got.

#1221 fix(citrus-kafka): delombok module
  endpoints/citrus-kafka/src/main/java/org/citrusframework/kafka/endpoint/KafkaConsumer.java
  endpoints/citrus-kafka/src/main/java/org/citrusframework/kafka/endpoint/KafkaEndpoint.java
  endpoints/citrus-kafka/src/main/java/org/citrusframework/kafka/endpoint/KafkaEndpointConfiguration.java
  endpoints/citrus-kafka/src/main/java/org/citrusframework/kafka/endpoint/KafkaMessageConsumerUtils.java
  endpoints/citrus-kafka/src/main/java/org/citrusframework/kafka/endpoint/KafkaMessageFilter.java
  endpoints/citrus-kafka/src/main/java/org/citrusframework/kafka/endpoint/KafkaMessageFilteringConsumer.java
  endpoints/citrus-kafka/src/main/java/org/citrusframework/kafka/endpoint/KafkaMessageSingleConsumer.java
  endpoints/citrus-kafka/src/main/java/org/citrusframework/kafka/endpoint/KafkaProducer.java
  endpoints/citrus-kafka/src/main/java/org/citrusframework/kafka/endpoint/selector/KafkaMessageByHeaderSelector.java
  pom.xml
Labels: Type: Maintenance, Prio: High, State: Review

#1219 enable parallel maven build
  .github/workflows/build.yml
  .github/workflows/lts.yml
Labels: Type: Maintenance, Prio: Low, State: Review

#1232 fix(deps): updated major dependencies
  connectors/citrus-kubernetes/src/test/resources/org/citrusframework/kubernetes/integration/KubernetesExecuteIT.xml
  connectors/citrus-kubernetes/src/test/resources/org/citrusframework/kubernetes/integration/KubernetesSendReceiveIT.xml
  pom.xml
  runtime/citrus-quarkus/pom.xml
Labels: Prio: High, Type: Dependencies

#1241 fix: message to be validated is logged
  validation/citrus-validation-xml/src/main/java/org/citrusframework/validation/xml/DomXmlMessageValidator.java
Labels: Type: Enhancement, Prio: Low, State: Review

#1244 feat(#1243): Add option to configure disable redirect for HttpClient
  endpoints/citrus-http/src/main/java/org/citrusframework/http/client/HttpClientBuilder.java
  endpoints/citrus-http/src/main/java/org/citrusframework/http/client/HttpEndpointConfiguration.java
  endpoints/citrus-http/src/main/java/org/citrusframework/http/config/annotation/HttpClientConfig.java
  endpoints/citrus-http/src/main/java/org/citrusframework/http/config/annotation/HttpClientConfigParser.java
  endpoints/citrus-http/src/main/java/org/citrusframework/http/config/xml/HttpClientParser.java
  endpoints/citrus-http/src/main/resources/org/citrusframework/schema/citrus-http-config.xsd
  endpoints/citrus-http/src/test/java/org/citrusframework/http/config/annotation/HttpClientConfigParserTest.java
  endpoints/citrus-http/src/test/java/org/citrusframework/http/config/xml/HttpClientParserTest.java
  endpoints/citrus-http/src/test/java/org/citrusframework/http/integration/HttpClientWithRedirectIT.java
  endpoints/citrus-http/src/test/resources/citrus-context.xml
  endpoints/citrus-http/src/test/resources/org/citrusframework/http/citrus-http-with-redirect-servlet.xml
  endpoints/citrus-http/src/test/resources/org/citrusframework/http/config/xml/HttpClientParserTest-context.xml
  endpoints/citrus-http/src/test/resources/org/citrusframework/http/integration/HttpClientWithRedirectDisabledIT.xml
  endpoints/citrus-http/src/test/resources/org/citrusframework/http/integration/HttpClientWithRedirectIT.xml
Labels: Type: Enhancement

#1246 fix(desp): multiple dependency updates
  pom.xml
  runtime/citrus-quarkus/pom.xml
Labels: Prio: High, Type: Dependencies
