Repository citrusframework/citrus, pull requests merged in 2024-01, with the labels that each got.

#1088 #1086: Extend Citrus functions documentation
  src/manual/functions.adoc
Labels: Prio: High, Type: Documentation

#1091 feat(#1089): kubernetes client config with auth token
  connectors/citrus-kubernetes/src/main/java/org/citrusframework/kubernetes/client/KubernetesClientBuilder.java
  connectors/citrus-kubernetes/src/main/java/org/citrusframework/kubernetes/config/CredentialValidator.java
  connectors/citrus-kubernetes/src/main/java/org/citrusframework/kubernetes/config/annotation/KubernetesClientConfig.java
  connectors/citrus-kubernetes/src/main/java/org/citrusframework/kubernetes/config/annotation/KubernetesClientConfigParser.java
  connectors/citrus-kubernetes/src/main/java/org/citrusframework/kubernetes/config/xml/KubernetesClientParser.java
  connectors/citrus-kubernetes/src/main/resources/org/citrusframework/schema/citrus-kubernetes-config.xsd
  connectors/citrus-kubernetes/src/test/java/org/citrusframework/kubernetes/config/CredentialValidatorTest.java
  connectors/citrus-kubernetes/src/test/java/org/citrusframework/kubernetes/config/annotation/KubernetesBadClientConfigParserTest.java
  connectors/citrus-kubernetes/src/test/java/org/citrusframework/kubernetes/config/annotation/KubernetesClientConfigParserTest.java
  connectors/citrus-kubernetes/src/test/java/org/citrusframework/kubernetes/config/xml/KubernetesBadClientParserTest.java
  connectors/citrus-kubernetes/src/test/java/org/citrusframework/kubernetes/config/xml/KubernetesClientParserTest.java
  connectors/citrus-kubernetes/src/test/resources/citrus-context.xml
  connectors/citrus-kubernetes/src/test/resources/org/citrusframework/kubernetes/config/xml/KubernetesBadClientParserTest-context.xml
  connectors/citrus-kubernetes/src/test/resources/org/citrusframework/kubernetes/config/xml/KubernetesClientParserTest-context.xml
  src/manual/endpoint-kubernetes.adoc
Labels: Type: Feature, Prio: High, State: WIP

#1096 fix(#1094): fix nested jar url issue
  core/citrus-api/src/main/java/org/citrusframework/spi/ClasspathResourceResolver.java
  core/citrus-api/src/test/java/org/citrusframework/spi/ClassPathResourceResolverTest.java
Labels: Type: Bug, Prio: High

#1098 remove comment and version from http xsd schema
  endpoints/citrus-http/src/main/resources/org/citrusframework/schema/citrus-http-testcase.xsd
Labels: Type: Maintenance, Prio: High

#1104 allow configuration of xml validator via constructor
  validation/citrus-validation-xml/src/main/java/org/citrusframework/validation/xml/DomXmlMessageValidator.java
  validation/citrus-validation-xml/src/main/java/org/citrusframework/validation/xml/schema/XmlSchemaValidation.java
  validation/citrus-validation-xml/src/test/java/org/citrusframework/validation/xml/DomXmlMessageValidatorTest.java
Labels: Type: Maintenance, Prio: High

#1075 Feature: Sharded Test Execution
  core/citrus-base/src/main/java/org/citrusframework/sharding/Shard.java
  core/citrus-base/src/main/java/org/citrusframework/sharding/ShardingConfiguration.java
  core/citrus-base/src/main/java/org/citrusframework/util/SystemProvider.java
  core/citrus-base/src/test/java/org/citrusframework/sharding/ShardTest.java
  core/citrus-base/src/test/java/org/citrusframework/sharding/ShardingConfigurationTest.java
  core/citrus-base/src/test/java/org/citrusframework/util/SystemProviderTest.java
  src/manual/runtimes-junit5.adoc
  src/manual/runtimes-sharded.adoc
  src/manual/runtimes.adoc
  validation/citrus-validation-xml/src/main/java/org/citrusframework/validation/xml/schema/XmlSchemaValidation.java
  validation/citrus-validation-xml/src/test/java/org/citrusframework/validation/xml/schema/XmlSchemaValidationTest.java
Labels: Type: Enhancement, Type: Feature, Prio: High, Type: Documentation, State: Review

#1111 feat(testng): shard data provider tests
  core/citrus-base/src/main/java/org/citrusframework/sharding/Shard.java
  core/citrus-base/src/test/java/org/citrusframework/sharding/ShardTest.java
  core/citrus-base/src/test/java/org/citrusframework/sharding/ShardingConfigurationTest.java
  src/manual/runtimes-junit5.adoc
  src/manual/runtimes-testng.adoc
Labels: Type: Enhancement, Prio: High, Type: Documentation, State: Review

#1112 minor dependency upgrades
  pom.xml
Labels: Prio: High, Type: Dependencies

#1114 fix(#1100): empty file resource returns true on exist
  core/citrus-api/src/main/java/org/citrusframework/spi/Resources.java
  core/citrus-api/src/test/java/org/citrusframework/spi/ResourcesTest.java
  core/citrus-api/src/test/resources/ResourcesTest/FileWithContent.json
  core/citrus-api/src/test/resources/ResourcesTest/FileWithoutContent.txt
Labels: Type: Bug, Prio: High
