Repository citrusframework/citrus, pull requests merged in 2024-04, with the labels that each got.

#1144 fix(#1143): let HttpMessageBuilder create messages with unique ids
  core/citrus-api/src/main/java/org/citrusframework/CitrusSettings.java
  core/citrus-base/src/main/java/org/citrusframework/message/DefaultMessage.java
  core/citrus-base/src/test/java/org/citrusframework/message/DefaultMessageTest.java
  endpoints/citrus-http/src/main/java/org/citrusframework/http/message/HttpMessage.java
  endpoints/citrus-http/src/main/java/org/citrusframework/http/message/HttpMessageBuilder.java
  endpoints/citrus-http/src/test/java/org/citrusframework/http/message/HttpMessageBuilderTest.java
  endpoints/citrus-http/src/test/java/org/citrusframework/http/message/HttpMessageTest.java
Labels: Type: Bug, Prio: High

#1149 test case execution time measurement
  core/citrus-api/pom.xml
  core/citrus-api/src/main/java/org/citrusframework/TestCase.java
  core/citrus-api/src/main/java/org/citrusframework/TestResult.java
  core/citrus-api/src/main/java/org/citrusframework/context/TestContext.java
  core/citrus-api/src/main/java/org/citrusframework/report/TestReporters.java
  core/citrus-api/src/main/java/org/citrusframework/report/TestResults.java
  core/citrus-api/src/main/java/org/citrusframework/spi/PropertiesLoader.java
  core/citrus-api/src/test/java/org/citrusframework/TestResultTest.java
  core/citrus-api/src/test/java/org/citrusframework/report/TestReportersTest.java
  core/citrus-base/src/main/java/org/citrusframework/DefaultTestCase.java
  core/citrus-base/src/main/java/org/citrusframework/common/DefaultTestLoader.java
  core/citrus-base/src/main/java/org/citrusframework/report/JUnitReporter.java
  core/citrus-base/src/main/java/org/citrusframework/report/LoggingReporter.java
  core/citrus-base/src/test/java/org/citrusframework/DefaultTestCaseTest.java
  core/citrus-base/src/test/java/org/citrusframework/message/ZipMessageTest.java
  core/citrus-base/src/test/java/org/citrusframework/report/JUnitReporterTest.java
  core/citrus-base/src/test/java/org/citrusframework/report/LoggingReporterTest.java
  core/citrus-base/src/test/java/org/citrusframework/report/TestResultsTest.java
  core/pom.xml
  runtime/citrus-cucumber/src/main/java/org/citrusframework/cucumber/CitrusLifecycleHooks.java
  runtime/citrus-cucumber/src/test/java/org/citrusframework/cucumber/backend/CitrusLifecycleHooksTest.java
  runtime/citrus-junit5/src/main/java/org/citrusframework/junit/jupiter/CitrusExtension.java
  runtime/citrus-junit5/src/main/java/org/citrusframework/junit/jupiter/spring/CitrusSpringExtension.java
Labels: Type: Feature, Prio: Medium, State: WIP

#1151 fix(#948): Log proper test step index on incremental Citrus tests
  core/citrus-base/src/main/java/com/consol/citrus/report/LoggingReporter.java
Labels: Type: Maintenance, Prio: High, State: WIP

#1154 json message validator access
  validation/citrus-validation-json/src/main/java/org/citrusframework/validation/json/JsonTextMessageValidator.java
  validation/citrus-validation-json/src/main/java/org/citrusframework/validation/json/schema/JsonSchemaValidation.java
  validation/citrus-validation-json/src/test/java/org/citrusframework/validation/json/JsonTextMessageValidatorTest.java
Labels: Type: Maintenance, Prio: High
