Repository citrusframework/citrus, pull requests merged in 2025-01, with the labels that each got.

#1287 #1240: Fix mismatching variable names in echo and print documentation
  src/manual/actions-echo.adoc
  src/manual/actions-print.adoc
Labels: Prio: Low, Type: Documentation

#1289 Do not reigster empty listeners
  runtime/citrus-junit5/src/main/java/org/citrusframework/junit/jupiter/JUnitJupiterEngine.java
Labels: Type: Bug, Prio: High, State: Review

#1299 fix: dependency updates
  pom.xml
Labels: Prio: High, Type: Dependencies

#1298 feat(function): add EscapeJsonFunction, test and doc
  src/manual/functions.adoc
  validation/citrus-validation-json/src/main/java/org/citrusframework/functions/core/EscapeJsonFunction.java
  validation/citrus-validation-json/src/test/java/org/citrusframework/functions/core/EscapeJsonFunctionUnitTest.java
Labels: Type: Feature, Prio: Medium, State: Review

#1301 add escape json function to registry
  core/citrus-base/src/main/java/org/citrusframework/functions/DefaultFunctionLibrary.java
  core/citrus-base/src/main/java/org/citrusframework/functions/core/EscapeJsonFunction.java
  core/citrus-base/src/test/java/org/citrusframework/functions/FunctionUtilsTest.java
  core/citrus-base/src/test/java/org/citrusframework/functions/core/EscapeJsonFunctionUnitTest.java
Labels: Type: Bug, Prio: High

#1306 chore: include template name in success message
  core/citrus-base/src/main/java/org/citrusframework/container/Template.java
Labels: Type: Enhancement, Prio: Medium, State: Review
